// AUTO-GENERATED by scripts/generate-image-previews.mjs — DO NOT EDIT.
// Regenerated on every build/dev (npm prebuild/predev). Gitignored.
// Size, and a tiny blurred copy, of every raster image in public/.

export type StaticImagePreview = { width: number; height: number; blurDataURL: string }

export const IMAGE_PREVIEWS: Record<string, StaticImagePreview> = {
  "/blog-media/boris-chernoy-post-1.jpg": { width: 714, height: 466, blurDataURL: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAgAA4BaJbACdAD8J/fHAagA/qLMpa9IFXiT2yy7VqHD3zFjFNHzrATRpsJ+csk1pwyx9ZyGUnI7+a0PcAAA" },
  "/blog-media/development-loop-2026.jpg": { width: 1200, height: 780, blurDataURL: "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoMAAgAA4BaJaQAA3AA/vR8CTgsAAAA" },
  "/git.png": { width: 1024, height: 1024, blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAwAA4BaJZwAAlvS+RgAAP731YZsgYeS3EgXTontctu4KYSxvyIS2OehtKcPFeVuo2QAAAA=" },
  "/icons/apple-touch-icon.png": { width: 180, height: 180, blurDataURL: "data:image/webp;base64,UklGRtoAAABXRUJQVlA4WAoAAAAQAAAACwAACwAAQUxQSE0AAAABb6CgbRtGhTPKo/pMIyIC1lT6BjCKbbvJTS+rJyLZR0okgAw0IAArLJGAp6Yhov8TcFjQVh2MqxnQYgFkXvhtHrIv3YDW6mDcZzCaOwBWUDggZgAAAPABAJ0BKgwADAADgFolpAAPgwraMA1oAAD+9906feaA5X6mv5cRI7PsrQnEsYc65m1fwRt8tVi1P4pFkm39KW2es1NstI4uGdY9LVf7cTI2RX6pC2yQQeJ2c/XDSPrBjwdPRwAAAA==" },
  "/icons/favicon-32.png": { width: 32, height: 32, blurDataURL: "data:image/webp;base64,UklGRtAAAABXRUJQVlA4WAoAAAAQAAAACwAACwAAQUxQSD8AAAABV6CgbRtGRVLkhXp2SERE9gnVhZpIdqoLqdJFAhK+DiIClOCAHgnoRUFE/3OLuE9TKHcABD98AIQplHeSeF4AVlA4IGoAAABQAgCdASoMAAwAA4BaJaQAEPd8Uj7/5KinIAAA/vX8q45VjI4/V6uL0BXnQZc6kpejz9tPkLLi4SWa3f5dEDdk/nrNZbwQYij9J5CPsxU1LX3cSr31uo6Ztbom9eN1UhSBLQtJn1DTUAAA" },
  "/icons/favicon-48.png": { width: 48, height: 48, blurDataURL: "data:image/webp;base64,UklGRs4AAABXRUJQVlA4WAoAAAAQAAAACwAACwAAQUxQSEAAAAABT6CgbRsGSlmX7I5pRETwJgVY1bZtY94XPp8BTgQVbgkSiOBfBLFFiOh/3pk4x0y8O3Qw+51g3qFPmfiewnEBVlA4IGgAAABQAgCdASoMAAwAA4BaJaQAD4QfKpTf1wKSsAAA/vb6l3pAB0/pvddoS2judE18vwXGqPm9itUeSRv4o/vuv4Vl64kyaPVTH5PyMGz24UAzY1R43un4I6o1m/jsdQuTKI3U0hYCVMAAAA==" },
  "/icons/icon-192.png": { width: 192, height: 192, blurDataURL: "data:image/webp;base64,UklGRsYAAABXRUJQVlA4WAoAAAAQAAAACwAACwAAQUxQSDkAAAABP0AgQLHGa1OLGxER/0k/sIokK05z/yLhiILEA04QgH8FkRDR/zywW2TcB74A3e8A/YG3RcY9sAEAVlA4IGYAAADwAQCdASoMAAwAA4BaJaQAD4MNTTHMLoAA/vfdOn3mgOV+pr+XESOz7K0JyZ8tkFv5iwB0fXbY/xSLJNv6Uts9ZqbZahDuhYQdEbWd2R2Xq1cxi8ShsfCrhhF31ilcTqdD7mAAAAA=" },
  "/icons/icon-512-maskable.png": { width: 512, height: 512, blurDataURL: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoMAAwAA4BaJaQAD48QeH1D6McAAP75UT5YtFn7rPcpLAOrgZx27OjYP7Vfi/2UZUgWNFiwVZyLMOM50kkB99UEDAKS7wqORhQPMAAA" },
  "/icons/icon-512.png": { width: 512, height: 512, blurDataURL: "data:image/webp;base64,UklGRsoAAABXRUJQVlA4WAoAAAAQAAAACwAACwAAQUxQSDsAAAABYB1JspJE4OX/iUNW7tztIs9CiIgJSFrwD3RpTbFQmJ0KG9iDnvBjdPjASw+FTdnXFJswM/lCkOBSGABWUDggaAAAANABAJ0BKgwADAADgFolpAAPgwgFOFbAAP733Tp95oDlfqa/lxEjs+ytCcSxhzrmbV/BG3y1WLU/ikWSblsV14PX9HD3Ugi52QE9psIpfhnJxUqFU1/DpVCqhAEXD8KPDcD8q8bAAAAA" },
  "/images/launch/step-1-new-repository.png": { width: 1269, height: 588, blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoMAAYAA4BaJZwAAxe5tMyAAP72lt6sVQNcVEhgAAA=" },
  "/images/launch/step-2-token-scopes.png": { width: 1268, height: 569, blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoMAAUAA4BaJZwAAudLlqcAAP72lRP+lAZlEuQkMAA=" },
  "/placeholders/home.jpg": { width: 1197, height: 577, blurDataURL: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoMAAYAA4BaJZwAAqGVwJuAAP68n+SJNsYokC3pOdicmCxP1JzGgzgIyAAAAA==" },
  "/placeholders/logo-dark.png": { width: 512, height: 512, blurDataURL: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQAgCdASoMAAwAA4BaJaQAD4ARdOoWcBRAAP70xCg19ckIUJ6wv8pfMFBKHC4WvxFxGhlME55vs5y/x1eL+93HPv+qMC9bNNxLidvdwBLQ+6Yk1VLfk97f9kRb4K6k/H40yehVPV9LMlyDkb1fxMfCLiJqAAAA" },
  "/placeholders/logo-light.png": { width: 512, height: 512, blurDataURL: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQAgCdASoMAAwAA4BaJaQAD4ARdW/6D3vysAAA/vKQW9+A0Osve9ncBd9qaY4bDAMXdnI3GpZMuTznFDx3ytwcPkF6Ytewlbi5lIJFCr3WBct66p/irNQ768KFja6JiLceKilhjDPe43Pookvf5AAAAAA=" },
  "/splash/ipad-landscape.png": { width: 2048, height: 1536, blurDataURL: "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoMAAkAA4BaJZwABAAAAP7z4IqbJmHkAAA=" },
  "/splash/ipad-portrait.png": { width: 1536, height: 2048, blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAABwAQCdASoMABAAA4BaJZwCsAFAAAD+8+CQRdt0ulz9j9lAAAA=" },
  "/splash/ipad-pro-11-landscape.png": { width: 2388, height: 1668, blurDataURL: "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoMAAgAA4BaJZwABAAAAP7z4Iqbg4Ql4AA=" },
  "/splash/ipad-pro-11-portrait.png": { width: 1668, height: 2388, blurDataURL: "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAgCdASoMABEAPu1iqU2ppaQiMAgBMB2JZwC+SDBsAAD+8IVb/BQ9WTHgAA==" },
  "/splash/ipad-pro-12-landscape.png": { width: 2732, height: 2048, blurDataURL: "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoMAAkAA4BaJZwABAAAAP7z4IqbJmHkAAA=" },
  "/splash/ipad-pro-12-portrait.png": { width: 2048, height: 2732, blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAABwAQCdASoMABAAA4BaJZwCsAFAAAD+8+CPqpu1dudtbZ8AAAA=" },
  "/splash/iphone-13-landscape.png": { width: 2532, height: 1170, blurDataURL: "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoMAAYAA4BaJZwABAAAAP7z4QCSEm2oQAA=" },
  "/splash/iphone-13-portrait.png": { width: 1170, height: 2532, blurDataURL: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAgCdASoMABoAPu1iqU2ppaOiMAgBMB2JZwC+SDBsAAD+8IUr/B138zPZgAAA" },
  "/splash/iphone-15-landscape.png": { width: 2556, height: 1179, blurDataURL: "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoMAAYAA4BaJZwABAAAAP7z4QCSEl4AAAA=" },
  "/splash/iphone-15-portrait.png": { width: 1179, height: 2556, blurDataURL: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAgCdASoMABoAPu1iqU2ppaOiMAgBMB2JZwC+SDBsAAD+8IUr/EZYokV4AAAA" },
  "/splash/iphone-15-pro-max-landscape.png": { width: 2796, height: 1290, blurDataURL: "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoMAAYAA4BaJZwABAAAAP7z4QCSEm2oQAA=" },
  "/splash/iphone-15-pro-max-portrait.png": { width: 1290, height: 2796, blurDataURL: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAgCdASoMABoAPu1iqU2ppaOiMAgBMB2JZwC+SDBsAAD+8IUr/B138zPZgAAA" },
  "/splash/iphone-8-landscape.png": { width: 1334, height: 750, blurDataURL: "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoMAAcAA4BaJZwABAAAAP7z4QCSEm2oQAA=" },
  "/splash/iphone-8-portrait.png": { width: 750, height: 1334, blurDataURL: "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAgCdASoMABUAPu1iqU2ppaQiMAgBMB2JZwC+SDBsAAD+8IVd47x9WTHgAA==" },
  "/splash/iphone-x-landscape.png": { width: 2436, height: 1125, blurDataURL: "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoMAAYAA4BaJZwABAAAAP7z4QCSEm2oQAA=" },
  "/splash/iphone-x-portrait.png": { width: 1125, height: 2436, blurDataURL: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAgCdASoMABoAPu1iqU2ppaQiMAgBMB2JZwC+SDBsAAD+8IUr/B138zPZgAAA" },
  "/splash/iphone-xr-landscape.png": { width: 1792, height: 828, blurDataURL: "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAABQAQCdASoMAAYAA4BaJZwABAAAAP7z4QCSEl4AAAA=" },
  "/splash/iphone-xr-portrait.png": { width: 828, height: 1792, blurDataURL: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAgCdASoMABoAPu1iqU2ppaOiMAgBMB2JZwC+SDBsAAD+8IUr/B138zPZgAAA" },
}
